//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1")]
public interface IService1
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/validarUsuario", ReplyAction="http://tempuri.org/IService1/validarUsuarioResponse")]
    string validarUsuario(string pStrUsuario, string pStrPassword);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/validarUsuario", ReplyAction="http://tempuri.org/IService1/validarUsuarioResponse")]
    System.Threading.Tasks.Task<string> validarUsuarioAsync(string pStrUsuario, string pStrPassword);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerOrden", ReplyAction="http://tempuri.org/IService1/obtenerOrdenResponse")]
    string obtenerOrden();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerOrden", ReplyAction="http://tempuri.org/IService1/obtenerOrdenResponse")]
    System.Threading.Tasks.Task<string> obtenerOrdenAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/guardarOrden", ReplyAction="http://tempuri.org/IService1/guardarOrdenResponse")]
    bool guardarOrden(string pStrOrden);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/guardarOrden", ReplyAction="http://tempuri.org/IService1/guardarOrdenResponse")]
    System.Threading.Tasks.Task<bool> guardarOrdenAsync(string pStrOrden);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerAticulo", ReplyAction="http://tempuri.org/IService1/obtenerAticuloResponse")]
    string obtenerAticulo();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerAticulo", ReplyAction="http://tempuri.org/IService1/obtenerAticuloResponse")]
    System.Threading.Tasks.Task<string> obtenerAticuloAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string validarUsuario(string pStrUsuario, string pStrPassword)
    {
        return base.Channel.validarUsuario(pStrUsuario, pStrPassword);
    }
    
    public System.Threading.Tasks.Task<string> validarUsuarioAsync(string pStrUsuario, string pStrPassword)
    {
        return base.Channel.validarUsuarioAsync(pStrUsuario, pStrPassword);
    }
    
    public string obtenerOrden()
    {
        return base.Channel.obtenerOrden();
    }
    
    public System.Threading.Tasks.Task<string> obtenerOrdenAsync()
    {
        return base.Channel.obtenerOrdenAsync();
    }
    
    public bool guardarOrden(string pStrOrden)
    {
        return base.Channel.guardarOrden(pStrOrden);
    }
    
    public System.Threading.Tasks.Task<bool> guardarOrdenAsync(string pStrOrden)
    {
        return base.Channel.guardarOrdenAsync(pStrOrden);
    }
    
    public string obtenerAticulo()
    {
        return base.Channel.obtenerAticulo();
    }
    
    public System.Threading.Tasks.Task<string> obtenerAticuloAsync()
    {
        return base.Channel.obtenerAticuloAsync();
    }
}
